CREATE TABLE ADDRESS (
    ID VARCHAR(36) NOT NULL,
    PUBLIC_PLACE VARCHAR(255) NOT NULL,
    NUMBER INT NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(9) NOT NULL,
    ADDRESS_TYPE VARCHAR(10) NOT NULL,
    MAIN BOOLEAN NOT NULL,
    PERSON_ID VARCHAR(36) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT FK_ADDRESS_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID));